### ISSUE TITLE
No version for raspberry?

### ISSUE THREAD

**Issue by dan-developer** [cztomczak/cefpython#578] opened 2020-06-06 21:55 UTC
I tried to install python on the raspberry but says it can't find any version.

![image](https://user-images.githubusercontent.com/10473169/83955250-28356400-a827-11ea-9462-3e95bc4f2805.png)

**Comment by cztomczak** [comment] 2020-06-06 22:51
No. Duplicate of #267.

**Closed by cztomczak** 2020-06-06 22:51 UTC
