### ISSUE TITLE
Support for Python 3.4 / 3.5 / 3.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#121] opened 2015-08-28 10:55 UTC
__Update 3__:

v56.0 for Mac with Python 3 support released, see: https://github.com/cztomczak/cefpython/releases/tag/v56.0

__Update 2__: 

Python 3.6 support added in v55.1 release for Linux:
https://github.com/cztomczak/cefpython/releases/tag/v55.1 

__Update 1__:

Python 3 beta release for Linux:
https://github.com/cztomczak/cefpython/releases/tag/v53.1

Tested with Python 3.4.5 / 3.5.2 and Cython 0.24.1 on Ubuntu 14.04. Only hello_world.py and unit tests were run and do work fine. Other examples may work but were not tested.

------------------------------------------

To compile with Python 3.4 it is required to update Cython to version 0.20 or later which added support for CPython 3.4. Update related to Cython upgrade will be occuring in Issue #110.

**Still TODO**:
-  In Makefiles there are defined includes like `-I/usr/include/Python2.7`. Currently it somehow works on Python 3 with the Python 2.7 include path. There are only a few macros in cefpython.h like PY_LONG_LONG and PyMODINIT_FUNC and these seem to be the same for Python 2 and 3. However a proper fix should be done. We could implement this as part of Issue #210 (Use CMake and Ninja on all platforms ).

**Comment by mese79** [comment] 2015-11-20 20:31
Hi
Is there any news for supporting python 3.x guys?

**Comment by jamiegau** [comment] 2016-03-27 06:46
It is now March, 2016...
Come on, lets move on from Python2.  I make it a rule to avoid python 2 if I can.
This looks like a great tool.. I would like to use it but I am very python3 centric with all my code.

**Comment by zelid** [comment] 2016-04-05 09:56
Still waiting for Python 3.5 for OS X 10.7+

**Comment by cztomczak** [comment] 2016-09-17 19:11
Initial Python 3 support added in commit 6f0d9b3af1ff4569266ca9d0cb5319e922597ff4. Tested with Python 3.4.5 and Cython 0.24.1 on Linux. Only minimal testing with the hello_world.py example was done. It's very probable that there are still issues with other examples. Further tests are needed.

**Comment by cztomczak** [comment] 2016-09-20 17:59
Python 3 beta release for Linux: https://github.com/cztomczak/cefpython/releases/tag/v53.1

**Comment by jimanvlad** [comment] 2017-01-12 14:53
Any news on Python 3 for windows?

**Comment by mflmartin** [comment] 2017-01-20 00:36
Windows Support for Python 3 would be HUGE!

**Comment by carlosperate** [comment] 2017-01-20 15:43
This issue might be more relevant for the windows platform: https://github.com/cztomczak/cefpython/issues/294

**Comment by caodixy** [comment] 2017-01-23 08:01
@carlosperate  could you  tell me the release time of windows 55+?

**Comment by carlosperate** [comment] 2017-01-23 09:31
I'm not the maintainer, will have to ask @cztomczak that.

**Comment by caodixy** [comment] 2017-01-23 09:57
@cztomczak  could you tell me the release time of windows 55+?

**Comment by cztomczak** [comment] 2017-03-03 21:31
v56.0 for Mac with Python 3 support released, see: https://github.com/cztomczak/cefpython/releases/tag/v56.0

**Comment by cztomczak** [comment] 2017-03-08 21:26
Added Python 3 support on Windows in commits 	5f24f50 and 7e4d587.
Tested with Python 3.4 / 3.5 / 3.6. Only 32-bit. Everything runs OK.

```
[_test_runner.py] CEF Python 56.0
[_test_runner.py] Python 3.6.0
[_test_runner.py] Ran 34 tests in total
[_test_runner.py] OK all unit tests succeeded
[build.py] Run examples
[run_examples.py] PASS: wxpython.py (wxPython not installed)
[run_examples.py] PASS: gtk2.py (Gtk 2 not installed
[run_examples.py] PASS: gtk3.py (Gtk 3 not installed)
[run_examples.py] PASS: qt4.py pyqt (PyQt4 not installed)
[run_examples.py] PASS: qt4.py pyside (PySide not installed)
[run_examples.py] Running 'hello_world.py'...
[hello_world.py] CEF Python 56.0
[hello_world.py] Python 3.6.0
[run_examples.py] Running 'tkinter_.py'...
[tkinter_.py] CEF Python 56.0
[tkinter_.py] Python 3.6.0
[tkinter_.py] Tk 8.6.6
[run_examples.py] SUMMARY:
  OK    hello_world.py
  OK    tkinter_.py
  PASS  wxpython.py
  PASS  gtk2.py
  PASS  gtk3.py
  PASS  qt4.py pyqt
  PASS  qt4.py pyside
[run_examples.py] OK(2). Passed: 5.
[build.py] Everything OK
```

**Comment by raphaelm** [comment] 2017-03-10 13:02
FYI, I was able to reproduce the successful windows build with Python 3.4. Thank you very very much for the good installation documentation. :heart:

**Comment by cztomczak** [comment] 2017-03-11 16:23
v56.0 for Windows released with Python 3 support and both 32-bit and 64-bit platforms support. See GH release: https://github.com/cztomczak/cefpython/releases/tag/v56.0-win

**Comment by cztomczak** [comment] 2017-03-11 16:24
Python 3 is now supported on all platforms. See GH releases pages or install using pip.

**Closed by cztomczak** 2017-03-11 16:23 UTC
Labels: next release
