### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by janEntikan** [cztomczak/cefpython#546] opened 2019-12-03 19:47 UTC
Importing cefpython with python 3.8 raised:
`Exception: Python version not supported: 3.8.0 (default, Oct 23 2019, 18:51:26)`

Arch Linux's package manager installs/updates to python 3.8. Downgrading is non-trivial.

**Comment by gregorias** [comment] 2019-12-25 13:46
If you use an Arch Linux distro, I can also recommend installing and using [python36](https://aur.archlinux.org/packages/python36/). I find it a more convenient stop-gap measure than downgrading.

**Comment by momojohobo** [comment] 2019-12-28 17:37
I ended up using pyenv. Thanks for the tip, though!

**Comment by coderextreme** [comment] 2020-04-10 14:19
A new release for python 3.8.1 would be welcome, for those of us who have already upgraded.  Thanks for your hard work!

**Comment by cztomczak** [comment] 2020-06-01 14:19
Take a look at commit 1c616296538fd2526961fe989f70cc735372b13f which added Python 3.7 support. It changed only a few files. To add Python 3.8 support make similar changes to these files. Then build it by following the build instructions. Pull requests are welcome.

**Comment by alexdelorenzo** [comment] 2020-06-06 19:43
Don't have the resources to spare to patch, build and test this project, but I'd love to use it with Python 3.8. Thanks for your work @cztomczak

**Comment by simonsan** [comment] 2020-06-13 01:37
Keep in mind:

Python 3.8 changes the behaviour of resolving DLLs on Windows. 

> DLL dependencies for extension modules and DLLs loaded with ctypes on Windows are now resolved more securely. Only the system paths, the directory containing the DLL or PYD file, and directories added with add_dll_directory() are searched for load-time dependencies. Specifically, PATH and the current working directory are no longer used, and modifications to these will no longer have any effect on normal DLL resolution. If your application relies on these mechanisms, you should check for add_dll_directory() and if it exists, use it to add your DLLs directory while loading your library. Note that Windows 7 users will need to ensure that Windows Update KB2533623 has been installed (this is also verified by the installer). (Contributed by Steve Dower in bpo-36085.)

Src.: https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew

**Comment by rlaPHOENiX** [comment] 2020-06-20 07:07
Just to mention, it works fine on Python 3.8 with literally no changes to the actual code other than how it's imported:

Change:
```
elif sys.version_info[:2] == (3, 7):
```

to:
```
elif sys.version_info[:2] in [(3, 7), (3, 8)]:
```

Works perfectly fine, been using it like this for months without encountering a single problem.

**Comment by cztomczak** [comment] 2020-06-20 09:20
This is not recommended.

**Comment by cztomczak** [comment] 2020-06-20 09:28
cefpython modules are compiled for specific Python versions. What you're doing is a hack and many bad things could happen to your app. This is unsupported and dangerous. You've been warned.

**Comment by rlaPHOENiX** [comment] 2020-06-20 09:32
> cefpython modules are compiled for specific Python versions. What you're doing is a hack and many bad things could happen to your app. This is unsupported and dangerous. You've been warned.

I'm aware, I tried to compile for python 3.8 on my own arch linux machine, but I encountered issues with pango trying to load hb.h (harfbuzz.h, which with some manual overrides fixed), and then issues with GTK in some way, eventually it just failed to compile. I was following the Build instructions in Knowledge Base file.

I know its a total hack and generally unsupported, but I've literally been using it in all kinds of setups for months without a single problem, and I'm not exaggerating.

**Comment by avollmerhaus** [comment] 2020-06-23 09:04
Ubuntu 20.04 comes with python3.8, so there's that :)

**Comment by matthewhampton** [comment] 2020-06-25 11:48
Hi @cztomczak. I'm trying to get this done based on your earlier advice.  (see https://github.com/j5int/cefpython/tree/cefpython66-py38 for WIP)

I'm starting on windows, and am getting one unittest failure and I was wondering if you could give me some pointers?

(It seems to be working OK)

This is the failure:

```
======================================================================
FAIL: test_main (main_test.MainTest_IsolatedTest)
Main entry point. All the code must run inside one
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mhampton\work\git\cefpython\unittests\main_test.py", line 304, in test_main
    check_auto_asserts(self, [] + client_handlers
  File "C:\Users\mhampton\work\git\cefpython\unittests\_common.py", line 88, in check_auto_asserts
    test_case.assertTrue(value, "Check assert: " +
AssertionError: False is not true : Check assert: GlobalHandler.HasDevTools_True

----------------------------------------------------------------------
```
And the root cause seems to be this:

```
29. browser.CloseBrowser() ok
Traceback (most recent call last):
  File "task.pyx", line 85, in cefpython_py38.PyTaskRunnable
  File "C:\Users\mhampton\work\git\cefpython\unittests\_common.py", line 134, in close_devtools
    global_handler.HasDevTools_True = main_browser.HasDevTools()
AttributeError: 'NoneType' object has no attribute 'HasDevTools'
```

Which leads to this func - so evidentally cef.GetBrowserByIdentifier(MAIN_BROWSER_ID) is returning None

```
def close_devtools(global_handler):
    main_browser = cef.GetBrowserByIdentifier(MAIN_BROWSER_ID)
    global_handler.HasDevTools_True = main_browser.HasDevTools()
    main_browser.CloseDevTools()
    subtest_message("DevTools popup ok")
```

Any help would be much appreciated.

**Comment by doanga2007** [comment] 2020-08-19 07:39
Importing cefpython with python 3.8.5 have not support raised at same:

`Exception: Python version not supported: 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:43:08)`

In **__init__.py** source code file , cefpython support python to 3.7.x (not plus to version 3.8.x).

```
# Copyright (c) 2013 CEF Python, see the Authors file.
# All rights reserved. Licensed under BSD 3-clause license.
# Project website: https://github.com/cztomczak/cefpython

# NOTE: Template variables like 66.0 are replaced with actual
#       values when make_installer.py tool generates this package
#       installer.

import os
import sys
import ctypes
import platform

__all__ = ["cefpython"]  # Disabled: "wx"
__version__ = "66.0"
__author__ = "The CEF Python authors"

# If package was installed using PIP or setup.py then package
# dir is here:
#   /usr/local/lib/python2.7/dist-packages/cefpython3/

# If this is a debian package then package_dir returns:
#   /usr/lib/pymodules/python2.7/cefpython3
# The above path consists of symbolic links to the real directory:
#   /usr/share/pyshared/cefpython3

package_dir = os.path.dirname(os.path.abspath(__file__))

# This loads the libcef.so library for the subprocess executable.
# On Mac it works without setting library paths.
os.environ["LD_LIBRARY_PATH"] = package_dir

# This env variable will be returned by cefpython.GetModuleDirectory().
os.environ["CEFPYTHON3_PATH"] = package_dir

# This loads the libcef library for the main python executable.
# Loading library dynamically using ctypes.CDLL is required on Linux.
# TODO: Check if on Linux libcef.so can be linked like on Mac.
# On Mac the CEF framework dependency information is added to
# the cefpython*.so module by linking to CEF framework.
# The libffmpegsumo.so library does not need to be loaded here,
# it may cause issues to load it here in the browser process.
if platform.system() == "Linux":
    libcef = os.path.join(package_dir, "libcef.so")
    ctypes.CDLL(libcef, ctypes.RTLD_GLOBAL)

# Load the cefpython module for given Python version
if sys.version_info[:2] == (2, 7):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py27 as cefpython
elif sys.version_info[:2] == (3, 4):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py34 as cefpython
elif sys.version_info[:2] == (3, 5):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py35 as cefpython
elif sys.version_info[:2] == (3, 6):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py36 as cefpython
elif sys.version_info[:2] == (3, 7):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py37 as cefpython
else:
    raise Exception("Python version not supported: " + sys.version)
```

I wait to cefpython support python 3.8.x and python future version (3.9.x, 3.10.x, 4.x.x, ... to **future.x.x** is version example: 9.x.x).

**Comment by mcejp** [comment] 2020-10-26 11:37
FWIW, I was able to build cefpython for Python 3.8 on Linux with some [minimal changes](https://github.com/mcejp/cefpython/commit/f4c0f0c06d52d154393002e7e779467b8bb369fe). I have yet to see how stable it is and I haven't really looked into the packaging concerns.

**Comment by cztomczak** [comment] 2020-10-26 12:02
It may also be a good idea to upgrade Cython to latest version since later versions fixed some Python 3.8 issues.

**Comment by Correct-Syntax** [comment] 2021-01-28 00:14
Hi there, I know that this is labeled "next release", but may I ask when the next release will be? I am really hoping to try cefpython with python 3.8. :)

**Comment by cztomczak** [comment] 2021-01-28 11:36
There will be a new release with Python 3.8 support in about two weeks.

**Comment by Correct-Syntax** [comment] 2021-01-28 13:56
@cztomczak, sounds good! 👍

**Closed** 2021-02-14 20:03 UTC
Labels: next release

**Comment by cztomczak** [comment] 2021-02-16 20:18
New v66.1 release for Windows with Python 3.8 / 3.9 support is ready: https://github.com/cztomczak/cefpython/releases/tag/v66.1

**Comment by aidos** [comment] 2021-02-17 20:53
@cztomczak are there plans to release a linux version soon? (I have no idea of the difference in work between it and the window release)

**Comment by All4Gis** [comment] 2021-07-01 12:42
Any plans for the linux version @cztomczak ? Amazing library

**Comment by Weiyi-Feng** [comment] 2021-12-28 08:11
Waiting for Linux support
