### ISSUE TITLE
dispaly error when excute exe at win 10 os

### ISSUE THREAD

**Issue by Jackjiayou** [cztomczak/cefpython#532] opened 2019-07-30 09:54 UTC
Questions should be asked on the forum:
https://groups.google.com/group/cefpython

Use pyisntaller.py generate exe  base on helloword.py of  examples and excute the exe is ok,but after add some fuction and import package use pyinstaller generate exe,Excte the exe in other notebook ,  bellow is the picture,  after click the page,will popup a same new ,open Devtool, bellow is the picture. In Devtool has double page.
But at some other  computer is ok .

When run pyinstaller to generate exe has some warning like ' WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\program files (x86)\microsoft visual studio\shared\python36_64\python36.dll',bellow is picture.
Thank you very much!
![Capture3](https://user-images.githubusercontent.com/43378246/62119455-33a82c80-b2f2-11e9-9397-3db194a1c132.PNG)

<img width="509" alt="Capture" src="https://user-images.githubusercontent.com/43378246/62118202-d7dca400-b2ef-11e9-93e1-1a6d1a3904cf.PNG">
<img width="526" alt="Capture9" src="https://user-images.githubusercontent.com/43378246/62118211-dc08c180-b2ef-11e9-956f-3078a6a0f609.PNG">

**Comment by cztomczak** [comment] 2019-07-30 10:06
See pyinstaller README for supported pyinstaller versions: https://github.com/cztomczak/cefpython/blob/master/examples/pyinstaller/README-pyinstaller.md

The warnings are issues with pyinstaller and should be reported to pyinstaller.

The screen issue looks like a DPI issue. I suggest you embed a DPI awareness manifest with your executable to fix it. See this comment for details: https://github.com/cztomczak/cefpython/issues/530#issuecomment-505066492

Probably duplicate of Issue #530.

**Closed by cztomczak** 2019-07-30 10:06 UTC

**Comment by cztomczak** [comment] 2019-08-20 09:06
@Jackjiayou I have updated my comment with instructions and example code: https://github.com/cztomczak/cefpython/issues/530#issuecomment-505066492
