### ISSUE TITLE
Provide a single same wxpython.py example for all plattforms (Win, Linux, Mac)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#159] opened 2015-08-28 10:55 UTC
Currently the wxpython.py example differs with several details on each platform.

Some differences:
- On Mac Shutdown is not being called after app.MainLoop(), instead it is called in OnClose.
- On Mac the ApplicationSettings.locales_dir_path is not set. Instead it is required to set the "locale_pak" command line switch.
- On Linux/Mac it is required to set paths to the locale/resources dirs. On Windows it is not required.
- Key codes differ on different platforms. Code that handles pressing F5, F12, Escape keys differs.
- On Linux/Mac it is required for paths to local resources to be prefixed with the "file://" protocol. On Windows you can just use "C:/path". Currently all wxpython.py examples use "file://", but there should be a comment about it.
- On Linux browser needs to be embedded inside wx.Panel for the application menu to work. On Windows this is not required.
- The code that imports the local module differs. On Windows it loads libcef.dll, on Linux libcef.so and on Mac libcef.dylib.
- On Mac the cefpython library must be imported the very first, before any other libraries such as wx (Issue 155).

It's hard to maintain multiple wxpython copies with all these differences. All 
these files should be exact copy of the same file and should check 
platform.system() to execute platform specific code.

Original issue reported on code.google.com by `czarek.t...@gmail.com` on 11 Jan 2015 at 5:05

**Comment by cztomczak** [comment] 2016-11-02 07:00
Duplicate of #269.

**Comment by cztomczak** [comment] 2017-03-03 16:16
Done. See the new wxpython.py example in the root examples/ directory.

**Closed by cztomczak** 2017-03-03 16:16 UTC
Labels: examples, good first issue, next release
